export {
    Github,
    Instagram,
    Telegram,
    X,
} from "@/icons/brand"

export {
    FilledAssets,
    FilledBack,
    FilledCalendar,
    FilledCheck,
    FilledCopy,
    FilledDatabase,
    FilledDestroyed,
    FilledDots,
    FilledDownArrow,
    FilledDownload,
    FilledDownloadAlt,
    FilledFile,
    FilledFilter,
    FilledForward,
    FilledHome,
    FilledImage,
    FilledIndeterminate,
    FilledKey,
    FilledLayer,
    FilledLeft,
    FilledLink,
    FilledLoader0,
    FilledLoader1,
    FilledLoader2,
    FilledLock,
    FilledLogin,
    FilledLogout,
    FilledMail,
    FilledPen,
    FilledPlus,
    FilledPortfolio,
    FilledRepo,
    FilledRight,
    FilledRoute,
    FilledSave,
    FilledSearch,
    FilledSettings,
    FilledShare,
    FilledSync,
    FilledTrash,
    FilledUnlock,
    FilledUpArrow,
    FilledUpload,
    FilledUploadAlt,
    FilledUser,
    FilledWarning,
} from "@/icons/filled"

export {
    OutlineAssets,
    OutlineBack,
    OutlineCalendar,
    OutlineCheck,
    OutlineCopy,
    OutlineDatabase,
    OutlineDestroyed,
    OutlineDots,
    OutlineDownArrow,
    OutlineDownload,
    OutlineDownloadAlt,
    OutlineFile,
    OutlineFilter,
    OutlineForward,
    OutlineHome,
    OutlineImage,
    OutlineIndeterminate,
    OutlineKey,
    OutlineLayer,
    OutlineLeft,
    OutlineLink,
    OutlineLoader0,
    OutlineLoader1,
    OutlineLoader2,
    OutlineLock,
    OutlineLogin,
    OutlineLogout,
    OutlineMail,
    OutlinePen,
    OutlinePlus,
    OutlinePortfolio,
    OutlineRepo,
    OutlineRight,
    OutlineRoute,
    OutlineSave,
    OutlineSearch,
    OutlineSettings,
    OutlineShare,
    OutlineSync,
    OutlineTrash,
    OutlineUnlock,
    OutlineUpArrow,
    OutlineUpload,
    OutlineUploadAlt,
    OutlineUser,
    OutlineWarning,
} from "@/icons/outline"

export type {
    IconProps
} from "@/icons/types"